steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y openssh-client
        mkdir -p ~/.ssh
        gcloud secrets versions access latest --secret=vm-ssh-key > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r main.py requirements.txt vmdeploy@34.93.165.244:/home/vmdeploy/
        
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vmdeploy@34.93.165.244 'pip3 install -r requirements.txt && pkill -f main.py || true && nohup python3 main.py > output.log 2>&1 &'

options:
  logging: CLOUD_LOGGING_ONLY
